

# This file was *autogenerated* from the file temp_main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
import time

exec(open("./Code/rna_poly.py").read())
exec(open("./Code/polytope_funs.py").read())
exec(open("./Code/SuboptFile.py").read())
exec(open("./Code/NopctFile.py").read())
exec(open("./Code/accuracy_analysis.py").read())
exec(open("./Code/FilenameToAccessionNumberTools.py").read())
exec(open("./Code/bb_algorithms.py").read())
exec(open("./Code/bb_merge_alg.py").read())


seq_list = "MaxAccuracyFiles/tRNA.txt" #needs to be changed

## Initializes Data files
PolytopeList = InitializePolytopes(seq_list)
Slices = OrderSlices(PolytopeList)
AccuracyData = CreateAccuracyData(seq_list, PolytopeList, Slices)
NameData = CreateNameData(seq_list)
u = FindBounds(seq_list) # do we need this? Seems like not
NSequences = len(PolytopeList)

## Imports the L value for lower bound on accuracy
## The code assumes that there is an identical Lfile.txt in the same directory 
L = getLValue("L.txt")

## Start of main

x = "0"
for i in range(_sage_const_1 , NSequences):
    x = x + "," + str(i)
Considering = [x]
while (len(Considering[_sage_const_0 ].split(",")) > _sage_const_2 ):
    x = Considering.pop(_sage_const_0 )
    x = x.split(",")
    Len = (len(x) + _sage_const_1 ) // _sage_const_2 
    y = x[_sage_const_0 ]
    for i in range(_sage_const_1 , Len):
        y = y + "," + x[i]
    z = x[Len]
    for i in range(Len+_sage_const_1 ,len(x)):
        z = z + "," + x[i]
    Considering.append(y)
    Considering.append(z) 

while (len(Considering) > _sage_const_2 ):
    print("Starting merge of", x, "and", y)
    x = Considering.pop(_sage_const_0 )
    y = Considering.pop(_sage_const_0 )
    z = x + "," + y
    Considering.append(z)

timing_data = open("time_data.txt","a")
timing_data.write("Started FinalMerge at " + str(time.strftime("%H:%M:%S, %D", time.localtime())) + "\n")
timing_data.close()

print("Starting FinalMerge")

RelIndices1 = [eval(i) for i in Considering[_sage_const_0 ].split(",")]
RelIndices2 = [eval(i) for i in Considering[_sage_const_1 ].split(",")]

FinalMerge("MergeData/S" + Considering[_sage_const_0 ] + ".txt", "MergeData/S" + Considering[_sage_const_1 ] + ".txt",
           "MergeData/FinalOutput.txt", PolytopeList, Slices, AccuracyData, NameData, L,
           "Lfile.txt", RelIndices1, RelIndices2)

timing_data = open("time_data.txt","a")
timing_data.write("Finished bb_main at " + str(time.strftime("%H:%M:%S, %D", time.localtime())))
timing_data.close()

